name: main
on: push
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: main
      shell: cmd
      run: |
        set PATH=C:\Miniconda;C:\Miniconda\Scripts;C:\msys64\ucrt64\bin;%PATH%
        where python
        python -m pip install mugideploy
